import type { Locale } from "@/lib/lang";

export interface HistoryPeriod {
  name: Record<Locale, string>;
  start: string;
  end: string;
  capital?: Record<Locale, string>;
  nation_name?: Record<Locale, string>;
  desc?: Record<Locale, string>;
  type: "independence" | "occupation" | "war";
}

export const HISTORY_DATA: HistoryPeriod[] = [
  {
    name: {
      vi: "Văn Lang",
      en: "Văn Lang",
      zh: "文郎",
      ja: "バンラン",
      ko: "반랑",
    },
    start: "2524 TCN",
    end: "257 TCN",
    type: "independence",
  },
  {
    name: {
      vi: "Âu Lạc",
      en: "Âu Lạc",
      zh: "瓯雒",
      ja: "アウラック",
      ko: "어울락",
    },
    start: "257 TCN",
    end: "179 TCN",
    type: "independence",
  },
  {
    name: {
      vi: "Nhà Triệu",
      en: "Triệu Dynasty",
      zh: "赵朝",
      ja: "趙朝",
      ko: "조 왕조",
    },
    start: "208 TCN",
    end: "111 TCN",
    type: "independence",
  },
  {
    name: {
      vi: "Bắc thuộc lần I",
      en: "First Chinese Domination",
      zh: "第一次北属",
      ja: "第一次北属期",
      ko: "제1차 북속기",
    },
    start: "111 TCN",
    end: "40",
    type: "occupation",
  },
  {
    name: {
      vi: "Hai Bà Trưng",
      en: "Trưng sisters",
      zh: "二征夫人",
      ja: "하이・バー・チュン",
      ko: "하이 바 쯩",
    },
    start: "40",
    end: "43",
    type: "independence",
  },
  {
    name: {
      vi: "Bắc thuộc lần II",
      en: "Second Chinese Domination",
      zh: "第二次北属",
      ja: "第二次北属期",
      ko: "제2차 북속기",
    },
    start: "43",
    end: "544",
    type: "occupation",
  },
  {
    name: {
      vi: "Nhà (Tiền) Lý",
      en: "Early Lý Dynasty",
      zh: "前李朝",
      ja: "前李朝",
      ko: "전 리 왕조",
    },
    start: "544",
    end: "602",
    type: "independence",
  },
  {
    name: {
      vi: "Bắc thuộc lần III",
      en: "Third Chinese Domination",
      zh: "第三次北属",
      ja: "第三次北属期",
      ko: "제3차 북속기",
    },
    start: "602",
    end: "939",
    type: "occupation",
  },
  {
    name: {
      vi: "Nhà Ngô",
      en: "Ngô Dynasty",
      zh: "吴朝",
      ja: "呉朝",
      ko: "응오 왕조",
    },
    start: "939",
    end: "965",
    type: "independence",
  },
  {
    name: {
      vi: "Loạn 12 sứ quân",
      en: "Anarchy of the 12 Warlords",
      zh: "十二使君之亂",
      ja: "十二使君의 란",
      ko: "십이사군의 난",
    },
    start: "966",
    end: "980",
    type: "war",
  },
  {
    name: {
      vi: "Nhà Đinh",
      en: "Đinh Dynasty",
      zh: "丁朝",
      ja: "丁朝",
      ko: "딘 왕조",
    },
    start: "968",
    end: "980",
    type: "independence",
  },
  {
    name: {
      vi: "Kháng chiến chống Tống I",
      en: "First resistance war against the Song",
      zh: "第一次宋越战争",
      ja: "第一次宋越戦争",
      ko: "제1차 송-대월 전쟁",
    },
    start: "981",
    end: "981",
    type: "war",
  },
  {
    name: {
      vi: "Nhà (Tiền) Lê",
      en: "Early Lê Dynasty",
      zh: "前黎朝",
      ja: "前黎朝",
      ko: "전 레 왕조",
    },
    start: "980",
    end: "1009",
    type: "independence",
  },
  {
    name: {
      vi: "Nhà Lý",
      en: "Lý Dynasty",
      zh: "李朝",
      ja: "李朝",
      ko: "리 왕조",
    },
    start: "1009",
    end: "1225",
    type: "independence",
  },
  {
    name: {
      vi: "Kháng chiến chống Tống II",
      en: "Second resistance war against the Song",
      zh: "第二次宋越战争",
      ja: "第二次宋越戦争",
      ko: "제2차 송-대월 전쟁",
    },
    start: "1075",
    end: "1077",
    type: "war",
  },
  {
    name: {
      vi: "Nhà Trần",
      en: "Trần Dynasty",
      zh: "陈朝",
      ja: "陳朝",
      ko: "쩐 왕조",
    },
    start: "1226",
    end: "1400",
    type: "independence",
  },
  {
    name: {
      vi: "Kháng chiến chống Mông - Nguyên I",
      en: "First resistance war against the Mongol and Yuan",
      zh: "第一次蒙越战争",
      ja: "第一次元越戦争",
      ko: "제1차 대월-몽골 전쟁",
    },
    start: "1257",
    end: "1258",
    type: "war",
  },
  {
    name: {
      vi: "Kháng chiến chống Mông - Nguyên II",
      en: "Second resistance war against the Mongol and Yuan",
      zh: "第二次蒙越战争",
      ja: "第二次元越戦争",
      ko: "제2차 대월-몽골 전쟁",
    },
    start: "1284",
    end: "1285",
    type: "war",
  },
  {
    name: {
      vi: "Kháng chiến chống Mông - Nguyên III",
      en: "Third resistance war against the Mongol and Yuan",
      zh: "第三次蒙越战争",
      ja: "第三次元越戦争",
      ko: "제3차 대월-몽골 전쟁",
    },
    start: "1287",
    end: "1288",
    type: "war",
  },
  {
    name: {
      vi: "Nhà Hồ",
      en: "Hồ Dynasty",
      zh: "胡朝",
      ja: "胡朝",
      ko: "호 왕조",
    },
    start: "1400",
    end: "1407",
    type: "independence",
  },
  {
    name: {
      vi: "Bắc thuộc lần IV",
      en: "Fourth Chinese Domination",
      zh: "第四次北属",
      ja: "第四次北属期",
      ko: "제4차 북속기",
    },
    start: "1407",
    end: "1427",
    type: "occupation",
  },
  {
    name: {
      vi: "Khởi nghĩa Lam Sơn",
      en: "Lam-Sơn uprising",
      zh: "蓝山起义",
      ja: "藍山蜂起",
      ko: "람선 봉기",
    },
    start: "1418",
    end: "1427",
    type: "occupation",
  },
  {
    name: {
      vi: "Nhà Lê (sơ)",
      en: "Early Later Lê Dynasty",
      zh: "黎初朝",
      ja: "黎初朝",
      ko: "레 왕조 (초기)",
    },
    start: "1428",
    end: "1527",
    type: "independence",
  },
  {
    name: {
      vi: "Nhà Mạc",
      en: "Mạc Dynasty",
      zh: "莫朝",
      ja: "莫朝",
      ko: "막 왕조",
    },
    start: "1527",
    end: "1593",
    type: "independence",
  },
  {
    name: {
      vi: "Nam - Bắc triều",
      en: "Northern and Southern dynasties",
      zh: "南北朝",
      ja: "南北朝",
      ko: "남북조 시대",
    },
    start: "1533",
    end: "1593",
    type: "war",
  },
  {
    name: {
      vi: "Nhà Lê Trung hưng - Đàng Ngoài",
      en: "Restored Lê Dynasty - Outer Realm",
      zh: "黎中兴朝 - 北河",
      ja: "黎中興朝 - 北河",
      ko: "레 왕조 (중흥) - 당 응아이",
    },
    start: "1533",
    end: "1787",
    type: "independence",
  },
  {
    name: {
      vi: "Đàng Trong",
      en: "Inner Realm (Nguyễn Lords)",
      zh: "南河 (阮主)",
      ja: "広南国 (阮主)",
      ko: "당 쫑 (응우옌 주)",
    },
    start: "1600",
    end: "1777",
    type: "independence",
  },
  {
    name: {
      vi: "Kháng chiến chống Thanh",
      en: "Resistance War against the Qing",
      zh: "清越战争",
      ja: "清越戦争",
      ko: "청-베트남 전쟁",
    },
    start: "1789",
    end: "1789",
    type: "war",
  },
  {
    name: {
      vi: "Kháng chiến chống Xiêm",
      en: "Resistance war against the Siamese",
      zh: "暹越战争",
      ja: "暹越戦争",
      ko: "시암-베트남 전쟁",
    },
    start: "1785",
    end: "1785",
    type: "war",
  },
  {
    name: {
      vi: "Nhà Tây Sơn",
      en: "Tây-Sơn Dynasty",
      zh: "西山朝",
      ja: "西山朝",
      ko: "떠이선 왕조",
    },
    start: "1778",
    end: "1802",
    type: "independence",
  },
  {
    name: {
      vi: "Nhà Nguyễn",
      en: "Nguyễn Dynasty",
      zh: "阮朝",
      ja: "阮朝",
      ko: "응우옌 왕조",
    },
    start: "1802",
    end: "1945",
    type: "independence",
  },
  {
    name: {
      vi: "Pháp thuộc",
      en: "French Protectorate",
      zh: "法属时期",
      ja: "フランス植民地時代",
      ko: "프랑스 식민지 시대",
    },
    start: "1858",
    end: "1945",
    type: "occupation",
  },
  {
    name: {
      vi: "Việt Nam Dân chủ Cộng hòa",
      en: "Democratic Republic of Vietnam",
      zh: "越南民主共和国",
      ja: "베트남民主共和国",
      ko: "베트남 민주 공화국",
    },
    start: "1945",
    end: "1976",
    type: "independence",
  },
  {
    name: {
      vi: "Kháng chiến chống Pháp",
      en: "Resistance War against the French",
      zh: "抗法战争",
      ja: "抗仏戦争",
      ko: "항프 전쟁",
    },
    start: "1946",
    end: "1954",
    type: "war",
  },
  {
    name: {
      vi: "Kháng chiến chống Mỹ",
      en: "Resistance War against the Americans",
      zh: "抗美战争",
      ja: "ベトナム戦争",
      ko: "베트남 전쟁",
    },
    start: "1954",
    end: "1975",
    type: "war",
  },
  {
    name: {
      vi: "Chiến tranh biên giới Tây Nam",
      en: "Cambodian - Vietnamese War",
      zh: "柬越戰爭",
      ja: "カンボジア・ベトナム戦争",
      ko: "베트남-캄보디아 전쟁",
    },
    start: "1978",
    end: "1989",
    type: "war",
  },
  {
    name: {
      vi: "Chiến tranh biên giới",
      en: "Sino - Vietnamese War",
      zh: "中越战争",
      ja: "中越戦争",
      ko: "중국-베트남 전쟁",
    },
    start: "1979",
    end: "1979",
    type: "war",
  },
  {
    name: {
      vi: "Cộng hòa Xã hội chủ nghĩa Việt Nam",
      en: "Socialist Republic of Vietnam",
      zh: "越南社会主义共和国",
      ja: "베트남社会主義共和国",
      ko: "베트남 사회주의 공화국",
    },
    start: "1975",
    end: "nay",
    type: "independence",
  },
];
